### ISSUE TITLE
Not working on solidus_core (= 2.10.0.beta1)

### ISSUE THREAD

**Issue by baraka2000** [boomerdigital/solidus_flexi_variants#23]
Hi There,

If anyone can help me here I'd appreciate it. Fresh solidus store on local dev. version 2.19.0.beta.

When I try to run the install I get:

rake aborted!
NoMethodError: undefined method `add_class' for #<Spree::Core::Environment::Calculators:0x00007fd602dbe478>

help me obi-wan, you're my only hope.
